version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql-ead-course
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ead-course
    ports:
      - '5433:5433'
    command: -p 5433
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - course-network
networks:
  course-network:
    driver: bridge

volumes:
  db:
    driver: local